ethereum_rpc = "https://eth-mainnet.g.alchemy.com/v2/WxXa9WSy5hOn3Yp9LUJ-j"
drosera_rpc = "https://relay.ethereum.drosera.io/"
eth_chain_id = 1
drosera_address = "0x01C344b8406c3237a6b9dbd06ef2832142866d87"

[traps]
[traps.aegis_v3_sentinel]
path = "out/AegisV3Sentinel.sol/AegisV3Sentinel.json"
response_contract = "0xab09B264F89DA35E7dCA82Ba01046e4c4D152d92"
response_function = "handleRisk(uint8,uint256,uint256,uint256)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 3
private_trap = true
whitelist = ["0x689Ad0f9cBa2dA64039cF894E9fB3Aa6266861D8"]
address = "0xFb2e59783cA7aEE91D5043442D7834AdC99c91b4"
